### ISSUE TITLE
compute_ev.py in project_commands.sh

### ISSUE THREAD

**Issue by mkmohangb** [ariaaay/clip2brain#1]
Currently when I run that step nothing happens. I assume this 

```python src/compute_ev.py --subj $subj --zscored_input```

has to be changed to

```python src/compute_ev.py --subj $subj --zscored_input --compute_ev```

Please confirm.

**Comment by ariaaay** [comment]
I think that's correct.

**Comment by ariaaay** [comment]
Shell script is fixed.
