### ISSUE TITLE
pycocotools src in repo

### ISSUE THREAD

**Issue by mkmohangb** [ariaaay/clip2brain#2]
I'm getting the following error when running ```extract_clip_features.py```:

ModuleNotFoundError: No module named 'pycocotools._mask'

If I remove the included ```pycocotools``` source and instead do ```pip install pycocotools``` then the error goes away.

Any reason to have ```pycocotools``` in source form in the repo?

**Comment by ariaaay** [comment]
i think I was using an older version of the pycocotools and was having some errors. Glad that works for you!

**Comment by ariaaay** [comment]
Issue resolved.
