### ISSUE TITLE
About the images

### ISSUE THREAD

**Issue by Brickkkkkk** [ariaaay/clip2brain#3]
Hello! I have some problems when I run the codes.
What's the format of NSD_images and where can I download them?

**Comment by ariaaay** [comment]
They should be available when you download the dataset from https://naturalscenesdataset.org/.

**Comment by geoffreyfan** [comment]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/1e35a3e6-abc2-47c1-a7b8-1e1867c95bd7)
Hello! The names of the 10,000 images being read from within are based on specific IDs. How can I obtain these 10,000 images that conform to the required code ID format?

**Comment by JustMuteAll** [comment]
These specific IDs are their IDs in COCO image dataset,instead of IDs in NSD dataset. An alternative solution is downloading the whole COCO 2017 train/val image dataset and set the COCO dataset as the stimuli folder.
