### ISSUE TITLE
What is the name of the cerebral cortex template used?

### ISSUE THREAD

**Issue by Sarah-air** [ariaaay/clip2brain#4]
What is the name of the cerebral cortex template used?

**Comment by ariaaay** [comment]
I am not sure what you are asking. Could you elaborate more? Is this for visualization purpose or extracting cortical voxels?

**Comment by ariaaay** [comment]
You can download the pycortex db at: https://drive.google.com/drive/folders/1YXAYggtlsfFxMtiqWs0UrMihxI125MHb?usp=sharing
