### ISSUE TITLE
About language_ROIs.npy

### ISSUE THREAD

**Issue by geoffreyfan** [ariaaay/clip2brain#6]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/e06c9723-f22b-455a-b35b-93aaed7046c6)
Hello! How was the file language_ROIs.npy generated? I couldn't find a file with this name in the generated npy files.

**Comment by ariaaay** [comment]
Hello, sorry about the late reply. I have graduated and currently don't have access to this file at the moment. This ROI is generated from another published paper. I am working on having this file available for download. Hopefully this doesn't cause more hiccups in using the code.

**Comment by Zhangzhixiang-laugh** [comment]
> Hello, sorry about the late reply. I have graduated and currently don't have access to this file at the moment. This ROI is generated from another published paper. I am working on having this file available for download. Hopefully this doesn't cause more hiccups in using the code.

Have you figured it out? Can language_ROIs.npy be provided?

**Comment by ariaaay** [comment]
Sorry for the delay. Here it is the file: https://drive.google.com/file/d/1MiaYSV4Cc8BisYyobsyrNP5XcvF7Ab0N/view?usp=sharing

**Comment by ariaaay** [comment]
Please add this citation when you use the language ROIs: 

> Fedorenko, Evelina, et al. "New method for fMRI investigations of language: defining ROIs functionally in individual subjects." Journal of neurophysiology 104.2 (2010): 1177-1194.
