### ISSUE TITLE
About the models 

### ISSUE THREAD

**Issue by geoffreyfan** [ariaaay/clip2brain#7]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/c7b48a28-1b2b-420a-ab1c-b8110487bee5)
Hello! Where can I download the model needed for the code?

**Comment by geoffreyfan** [comment]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/720560f8-11b1-4eda-b4cf-3696d012bc4e)

**Comment by ariaaay** [comment]
Hey! Sorry for the late reply during the holidays.
You can find the models on https://github.com/facebookresearch/SLIP?tab=readme-ov-file, under ViT-base.
