### ISSUE TITLE
About the pycortex/db/subj01

### ISSUE THREAD

**Issue by geoffreyfan** [ariaaay/clip2brain#8]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/61e35640-df97-4a1b-a0f5-4f4de00e6436)
Hello! Could you please make the subject files related to the NSD dataset under pycortex/db public? I am very interested in the transforms and mask parts contained within. Currently, we are missing these files for our visualizations. Thank you very much!

**Comment by ariaaay** [comment]
Here you go: https://drive.google.com/drive/folders/1YXAYggtlsfFxMtiqWs0UrMihxI125MHb?usp=sharing
