### ISSUE TITLE
About ./output/voxels_masks/language_ROIs.npy

### ISSUE THREAD

**Issue by geoffreyfan** [ariaaay/clip2brain#9]
![image](https://github.com/ariaaay/clip2brain/assets/105597268/ec721629-48df-4f99-a9f5-7a2111be42d3)

**Comment by Chris36839** [comment]
Hi, do you know how to get pictures in the “StimuliDir”?

**Comment by geoffreyfan** [comment]
> Hi, do you know how to get pictures in the “StimuliDir”?

NSD dataset：https://natural-scenes-dataset.s3.amazonaws.com/index.html
However, after you download it, the image data is in HDF5 format. You need to convert it into individual images with COCO annotations, which I haven't figured out how to do yet.

**Comment by Chris36839** [comment]
> > Hi, do you know how to get pictures in the “StimuliDir”?
> 
> NSD dataset：https://natural-scenes-dataset.s3.amazonaws.com/index.html However, after you download it, the image data is in HDF5 format. You need to convert it into individual images with COCO annotations, which I haven't figured out how to do yet.

OK, thanks!

**Comment by geoffreyfan** [comment]
> Hi, do you know how to get pictures in the “StimuliDir”?

My QQ is 3563678218. Shall we discuss together?

**Comment by Zhangzhixiang-laugh** [comment]
> ![image](https://private-user-images.githubusercontent.com/105597268/319918362-ec721629-48df-4f99-a9f5-7a2111be42d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDY1NDQsIm5iZiI6MTczMTE0NjI0NCwicGF0aCI6Ii8xMDU1OTcyNjgvMzE5OTE4MzYyLWVjNzIxNjI5LTQ4ZGYtNGY5OS1hOWY1LTdhMjExMWJlNDJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTU3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGEzMTA1NGI4NTFlODBmZGQxNWMxMjE1M2E5MjVlZDAwZTk2NzVkNzhkYjRlMGVlODVmYjIyNDljOTAwNzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VzC5bJx3k8dXFJfyx5eTbxYXAzp82vIICm-vi2apt0o)

Have you figured it out? Any suggestions for replication? Thanks.

**Comment by ariaaay** [comment]
Here is the language ROI file: https://drive.google.com/file/d/1MiaYSV4Cc8BisYyobsyrNP5XcvF7Ab0N/view?usp=sharing

**Comment by ariaaay** [comment]
Please add this citation when you use the language ROIs: 

> Fedorenko, Evelina, et al. "New method for fMRI investigations of language: defining ROIs functionally in individual subjects." Journal of neurophysiology 104.2 (2010): 1177-1194.
